version: "3.9"

services:
  backend:
    build: ./Backend
    restart: on-failure
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - service

    volumes:
      - /var/www/go-modules/limbic-api/Backend:/app

  service:
    build: ./Service
    restart: always
    ports:
      - "50052:50052"
  db:
    image: postgres:14
    restart: always
    env_file: .env
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data/



volumes:
  postgres_data: