version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=CSSE1810da
      - POSTGRES_DB=limbic

    ports:
      - "5432:5432"
volumes:
  postgres_data: